# ------------------------- #
# Version: 0.6.5
#
# Setup
#  1. Add a pipeline variable named PROJECT_ROOT
#  2. Add a pipeline variable named ITCH_SLUG
#  2. Add a pipeline variable named ITCH_SUFFIX
#  3. Choose which stages to run by uncommenting any of the following
.pages:
  extends: .build-pages
.win:
  extends: .build-deploy:win
.macos:
  extends: .build-deploy:macos
.web:
  extends: .build-deploy:web
# ------------------------- #

# Pipeline Variables
variables:
  PROJECT_LOCATION: $CI_PROJECT_DIR/$PROJECT_ROOT
  BUILD_LOCATION: $CI_PROJECT_DIR/Builds/$BUILD_PLATFORM

# GitLab Pages Deployment
.build-pages:
  stage: build
  only: [ develop ]
  needs: []
  image: tsgkadot/docker-docfx
  script: |
    docfx $PROJECT_LOCATION/Documentation/docfx.json
    mv $PROJECT_LOCATION/_site public
  artifacts:
    paths: [ public ]

# Unity Build and itch.io Deployment
.build-deploy:
  stage: build
  only: [ master, develop ]
  tags:
    - unity
  variables:
    GIT_DEPTH: 1
    GIT_CLEAN_FLAGS: -fd
  script:
    - |
      revision=$(git rev-parse --short HEAD)
      echo "Building revision $revision for $BUILD_PLATFORM..."
      goo project build "$PROJECT_LOCATION" -- \
        -logfile log.txt \
        -buildTarget "$BUILD_PLATFORM" \
        -executeMethod Andtech.BuildUtility.Builder.Build \
        -revision "$revision" \
        -output "$BUILD_LOCATION"
    - |
      channel="$ITCH_CHANNEL"
      if [[ "$ITCH_SUFFIX" =~ ^[^.].*	]]
      then
          channel="$channel-$ITCH_SUFFIX"
      fi
      if ! [[ "$CI_COMMIT_BRANCH" =~ ^(master|main)$	]]
      then
          channel="$channel-head"
      fi

      itchTarget="$ITCH_USER/$ITCH_SLUG:$channel"
      echo "Publishing as $itchTarget..."
      butler push "$BUILD_LOCATION" "$itchTarget"
  after_script:
    - |
      cat log.txt

# Helper Stages
.build-deploy:win:
  extends: .build-deploy
  variables:
    BUILD_PLATFORM: "StandaloneWindows64"
    ITCH_CHANNEL: "win"
.build-deploy:macos:
  extends: .build-deploy
  variables:
    BUILD_PLATFORM: "StandaloneOSX"
    ITCH_CHANNEL: "osx"
.build-deploy:web:
  extends: .build-deploy
  variables:
    BUILD_PLATFORM: "WebGL"
    ITCH_CHANNEL: "html"

